# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ceZnqt6-WJNUdaKv78gBURnAkBynhwmG
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import os

# -----------------------------
# 1. File paths
# -----------------------------
RAW_DATA_PATH = "/content/drive/MyDrive/ML Ops/Dataset/raw/heart.csv.csv"
PROCESSED_DATA_PATH = "/content/drive/MyDrive/ML Ops/Dataset/preprocessed/processed_heart_data.csv"

# Column names (dataset has no header)
COLUMNS = [
    "age", "sex", "cp", "trestbps", "chol", "fbs",
    "restecg", "thalach", "exang", "oldpeak",
    "slope", "ca", "thal", "target"
]

# -----------------------------
# 2. Load data
# -----------------------------
def load_data():
    print("Loading raw data...")
    df = pd.read_csv(RAW_DATA_PATH, header=None, names=COLUMNS)
    return df

# -----------------------------
# 3. Clean data
# -----------------------------
def clean_data(df):
    print("Cleaning data...")

    # Replace '?' with NaN
    df.replace("?", np.nan, inplace=True)

    # Convert columns to numeric
    for col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # Fill missing values with median
    df.fillna(df.median(), inplace=True)

    # Convert target to binary (0 = no disease, 1 = disease)
    df["target"] = df["target"].apply(lambda x: 1 if x > 0 else 0)

    return df

# -----------------------------
# 4. Save cleaned data
# -----------------------------
def save_data(df):
    os.makedirs("data/processed", exist_ok=True)
    df.to_csv(PROCESSED_DATA_PATH, index=False)
    print(f"Cleaned data saved to {PROCESSED_DATA_PATH}")

# -----------------------------
# 5. Main function
# -----------------------------
def main():
    df = load_data()
    df = clean_data(df)
    save_data(df)

    print("\nData preprocessing completed successfully!")
    print(df.head())

if __name__ == "__main__":
    main()